api:
  id: "18321741"

slack:
  id: "18321741"
  clientId: "xxx"
  clientSecret: "xxx"
  scopes: "users:read chat:write channels:read"
  callback: "/callback"
  authorize: "/authorize"
  callbackUrl: "https://127.0.0.1:8081/callback"
  
