slack:
  clientId: "14a8ac11d11c4a57b7b4aa372710d910"
  clientSecret: "2f06D7d0a0924857be933E91b8CeffdF"
  scopes: "chat:write:user"
  baseUrl: "/api"
  host: "513bb6f23f1142aea8feb534c31d2694.us-e2.cloudhub.io"
  
  
state:
  url: "https://anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/d62c7af1-de8e-416d-aad4-3f7b5916496e/openlogix-statecontrol-sapi/1.0.0/m/state"
  
dummy:
  url: ""
  