#%RAML 1.0 SecurityScheme
type: x-client-Credentials
describedBy:
  headers:
    clientId:
      type: string
      required: true
      example: "likitha"
    clientSecret:
      type: string
      required: true
      example: "supriya"
  responses:
    401:
      description: "401-Unauthorized access"