#%RAML 1.0 Trait
responses:
  400:
    description: Bad request
    body:
      example: {
        message: "Bad request",
        errorDetail: "Sent Wrong Information"
      }
  
  500:
    description: Internal Server Error
    body:
      example: {
        message: "Internal Server Error",
        errorDetail: "Sent Wrong Information"
      }